// Code generated by MockGen. DO NOT EDIT.
// Source: artist.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "spotify/dto"
	common "spotify/helper/common"

	gomock "github.com/golang/mock/gomock"
)

// MockArtistService is a mock of ArtistService interface.
type MockArtistService struct {
	ctrl     *gomock.Controller
	recorder *MockArtistServiceMockRecorder
}

// MockArtistServiceMockRecorder is the mock recorder for MockArtistService.
type MockArtistServiceMockRecorder struct {
	mock *MockArtistService
}

// NewMockArtistService creates a new mock instance.
func NewMockArtistService(ctrl *gomock.Controller) *MockArtistService {
	mock := &MockArtistService{ctrl: ctrl}
	mock.recorder = &MockArtistServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistService) EXPECT() *MockArtistServiceMockRecorder {
	return m.recorder
}

// AddArtist mocks base method.
func (m *MockArtistService) AddArtist(ctx context.Context, ArtistIn dto.Artist) common.SubReturnCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArtist", ctx, ArtistIn)
	ret0, _ := ret[0].(common.SubReturnCode)
	return ret0
}

// AddArtist indicates an expected call of AddArtist.
func (mr *MockArtistServiceMockRecorder) AddArtist(ctx, ArtistIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArtist", reflect.TypeOf((*MockArtistService)(nil).AddArtist), ctx, ArtistIn)
}

// GetAllArtist mocks base method.
func (m *MockArtistService) GetAllArtist(ctx context.Context) ([]dto.Artist, common.SubReturnCode) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllArtist", ctx)
	ret0, _ := ret[0].([]dto.Artist)
	ret1, _ := ret[1].(common.SubReturnCode)
	return ret0, ret1
}

// GetAllArtist indicates an expected call of GetAllArtist.
func (mr *MockArtistServiceMockRecorder) GetAllArtist(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArtist", reflect.TypeOf((*MockArtistService)(nil).GetAllArtist), ctx)
}

// GetArtistByID mocks base method.
func (m *MockArtistService) GetArtistByID(ctx context.Context, id uint) (dto.Artist, common.SubReturnCode) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByID", ctx, id)
	ret0, _ := ret[0].(dto.Artist)
	ret1, _ := ret[1].(common.SubReturnCode)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockArtistServiceMockRecorder) GetArtistByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockArtistService)(nil).GetArtistByID), ctx, id)
}

// GetArtistByName mocks base method.
func (m *MockArtistService) GetArtistByName(ctx context.Context, name string) ([]dto.Artist, common.SubReturnCode) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByName", ctx, name)
	ret0, _ := ret[0].([]dto.Artist)
	ret1, _ := ret[1].(common.SubReturnCode)
	return ret0, ret1
}

// GetArtistByName indicates an expected call of GetArtistByName.
func (mr *MockArtistServiceMockRecorder) GetArtistByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByName", reflect.TypeOf((*MockArtistService)(nil).GetArtistByName), ctx, name)
}

// UpdateArtist mocks base method.
func (m *MockArtistService) UpdateArtist(ctx context.Context, ArtistIn dto.Artist) common.SubReturnCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArtist", ctx, ArtistIn)
	ret0, _ := ret[0].(common.SubReturnCode)
	return ret0
}

// UpdateArtist indicates an expected call of UpdateArtist.
func (mr *MockArtistServiceMockRecorder) UpdateArtist(ctx, ArtistIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArtist", reflect.TypeOf((*MockArtistService)(nil).UpdateArtist), ctx, ArtistIn)
}
