// Code generated by MockGen. DO NOT EDIT.
// Source: song.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "spotify/dto"
	models "spotify/models"

	gomock "github.com/golang/mock/gomock"
)

// MockSongRepository is a mock of SongRepository interface.
type MockSongRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSongRepositoryMockRecorder
}

// MockSongRepositoryMockRecorder is the mock recorder for MockSongRepository.
type MockSongRepositoryMockRecorder struct {
	mock *MockSongRepository
}

// NewMockSongRepository creates a new mock instance.
func NewMockSongRepository(ctrl *gomock.Controller) *MockSongRepository {
	mock := &MockSongRepository{ctrl: ctrl}
	mock.recorder = &MockSongRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSongRepository) EXPECT() *MockSongRepositoryMockRecorder {
	return m.recorder
}

// AddSong mocks base method.
func (m *MockSongRepository) AddSong(ctx context.Context, songIn dto.Song) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSong", ctx, songIn)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSong indicates an expected call of AddSong.
func (mr *MockSongRepositoryMockRecorder) AddSong(ctx, songIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSong", reflect.TypeOf((*MockSongRepository)(nil).AddSong), ctx, songIn)
}

// AddSongToPlayList mocks base method.
func (m *MockSongRepository) AddSongToPlayList(ctx context.Context, songId, playlistId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSongToPlayList", ctx, songId, playlistId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSongToPlayList indicates an expected call of AddSongToPlayList.
func (mr *MockSongRepositoryMockRecorder) AddSongToPlayList(ctx, songId, playlistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSongToPlayList", reflect.TypeOf((*MockSongRepository)(nil).AddSongToPlayList), ctx, songId, playlistId)
}

// GetAllSong mocks base method.
func (m *MockSongRepository) GetAllSong(ctx context.Context) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSong", ctx)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSong indicates an expected call of GetAllSong.
func (mr *MockSongRepositoryMockRecorder) GetAllSong(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSong", reflect.TypeOf((*MockSongRepository)(nil).GetAllSong), ctx)
}

// GetSongByAlbumID mocks base method.
func (m *MockSongRepository) GetSongByAlbumID(ctx context.Context, albumId uint) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByAlbumID", ctx, albumId)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByAlbumID indicates an expected call of GetSongByAlbumID.
func (mr *MockSongRepositoryMockRecorder) GetSongByAlbumID(ctx, albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByAlbumID", reflect.TypeOf((*MockSongRepository)(nil).GetSongByAlbumID), ctx, albumId)
}

// GetSongByArtistID mocks base method.
func (m *MockSongRepository) GetSongByArtistID(ctx context.Context, artistId uint) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByArtistID", ctx, artistId)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByArtistID indicates an expected call of GetSongByArtistID.
func (mr *MockSongRepositoryMockRecorder) GetSongByArtistID(ctx, artistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByArtistID", reflect.TypeOf((*MockSongRepository)(nil).GetSongByArtistID), ctx, artistId)
}

// GetSongByID mocks base method.
func (m *MockSongRepository) GetSongByID(ctx context.Context, id uint) (models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByID", ctx, id)
	ret0, _ := ret[0].(models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByID indicates an expected call of GetSongByID.
func (mr *MockSongRepositoryMockRecorder) GetSongByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByID", reflect.TypeOf((*MockSongRepository)(nil).GetSongByID), ctx, id)
}

// GetSongByName mocks base method.
func (m *MockSongRepository) GetSongByName(ctx context.Context, name string) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByName", ctx, name)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByName indicates an expected call of GetSongByName.
func (mr *MockSongRepositoryMockRecorder) GetSongByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByName", reflect.TypeOf((*MockSongRepository)(nil).GetSongByName), ctx, name)
}

// GetSongByPlayListID mocks base method.
func (m *MockSongRepository) GetSongByPlayListID(ctx context.Context, id uint) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongByPlayListID", ctx, id)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongByPlayListID indicates an expected call of GetSongByPlayListID.
func (mr *MockSongRepositoryMockRecorder) GetSongByPlayListID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongByPlayListID", reflect.TypeOf((*MockSongRepository)(nil).GetSongByPlayListID), ctx, id)
}

// GetSongLikedByUserID mocks base method.
func (m *MockSongRepository) GetSongLikedByUserID(ctx context.Context, userId uint) ([]models.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongLikedByUserID", ctx, userId)
	ret0, _ := ret[0].([]models.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongLikedByUserID indicates an expected call of GetSongLikedByUserID.
func (mr *MockSongRepositoryMockRecorder) GetSongLikedByUserID(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongLikedByUserID", reflect.TypeOf((*MockSongRepository)(nil).GetSongLikedByUserID), ctx, userId)
}

// RemoveSongToPlayList mocks base method.
func (m *MockSongRepository) RemoveSongToPlayList(ctx context.Context, songId, playlistId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSongToPlayList", ctx, songId, playlistId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSongToPlayList indicates an expected call of RemoveSongToPlayList.
func (mr *MockSongRepositoryMockRecorder) RemoveSongToPlayList(ctx, songId, playlistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSongToPlayList", reflect.TypeOf((*MockSongRepository)(nil).RemoveSongToPlayList), ctx, songId, playlistId)
}
